import type { Metadata } from "next";

import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import "./components/common.css";

import { Marcellus, Jost } from "next/font/google";

export const marcellus = Marcellus({
  subsets: ["latin"],
  weight: ["400"], // only supported weight
  display: "swap",
});

export const jost = Jost({
  subsets: ["latin"],
  weight: ["400"], // only supported weight
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`$ antialiased`}
      >
         <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
